apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort    # convenient for Minikube
  selector:
    app: nextjs-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
